import { IHexagon } from '../types';
import { hexList } from './hexList';

export const vertexAdjacentHexes: IHexagon[][] = [
    [hexList()[0]],
    [hexList()[0]],
    [hexList()[0], hexList()[1]],
    [hexList()[1]],
    [hexList()[1], hexList()[2]],
    [hexList()[2]],
    [hexList()[2]],

    [hexList()[3]],
    [hexList()[3], hexList()[0]],
    [hexList()[3], hexList()[0], hexList()[4]],
    [hexList()[0], hexList()[1], hexList()[4]],
    [hexList()[4], hexList()[1], hexList()[5]],
    [hexList()[1], hexList()[5], hexList()[2]],
    [hexList()[2], hexList()[5], hexList()[6]],
    [hexList()[2], hexList()[6]],
    [hexList()[6]],

    [hexList()[7]],
    [hexList()[7], hexList()[3]],
    [hexList()[7], hexList()[3], hexList()[8]],
    [hexList()[8], hexList()[3], hexList()[4]],
    [hexList()[4], hexList()[8], hexList()[9]],
    [hexList()[4], hexList()[5], hexList()[9]],
    [hexList()[5], hexList()[9], hexList()[10]],
    [hexList()[5], hexList()[10], hexList()[6]],
    [hexList()[6], hexList()[10], hexList()[11]],
    [hexList()[6], hexList()[11]],
    [hexList()[11]],

    [hexList()[7]],
    [hexList()[7], hexList()[12]],
    [hexList()[7], hexList()[12], hexList()[8]],
    [hexList()[12], hexList()[8], hexList()[13]],
    [hexList()[8], hexList()[13], hexList()[9]],
    [hexList()[13], hexList()[9], hexList()[14]],
    [hexList()[9], hexList()[14], hexList()[10]],
    [hexList()[14], hexList()[10], hexList()[15]],
    [hexList()[10], hexList()[15], hexList()[11]],
    [hexList()[15], hexList()[11]],
    [hexList()[11]],

    [hexList()[12]],
    [hexList()[12], hexList()[16]],
    [hexList()[12], hexList()[16], hexList()[13]],
    [hexList()[16], hexList()[13], hexList()[17]],
    [hexList()[13], hexList()[17], hexList()[14]],
    [hexList()[17], hexList()[14], hexList()[18]],
    [hexList()[14], hexList()[18], hexList()[15]],
    [hexList()[18], hexList()[15]],
    [hexList()[18]],

    [hexList()[16]],
    [hexList()[16]],
    [hexList()[16], hexList()[17]],
    [hexList()[17]],
    [hexList()[17], hexList()[18]],
    [hexList()[18]],
    [hexList()[18]],
]
